name: jaspr_og
description: A library that can generate opengraph images based on jaspr components.
version: 0.0.1-dev.3
repository: https://github.com/Lexedia/jaspr_og
publish_to: https://pub.lexedia.moe

environment:
  sdk: ^3.10.0

dependencies:
  path: ^1.9.0
  jaspr: ^0.22.3
  takumi:
    hosted: https://pub.lexedia.moe
    version: ^0.0.1-dev.1
  shelf: ^1.4.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
